version: "3.7"
services:
  web: 
    image: nginx:latest
    container_name: nginx
    restart: always
    ports: 
      - "8080:80"
      - "465:465"
    volumes:
    - ./:/var/www
    - ./docker-conf/nginx:/etc/nginx/conf.d
    networks:
    - goncalves

  php:
    build: .
    container_name: php
    volumes:
    - ./:/var/www
    networks:
      - goncalves
  
  db:
    image: mysql:8.0.28
    container_name: mysql
    ports:
     - "3306:3306"
    restart: always
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./docker-conf/mysql:/docker-entrypoint-initdb.d
      - db-volume:/var/lib/mysql
    networks:
      - goncalves

volumes:
  db-volume:

networks:
  goncalves:
    driver: bridge
